server:
  port: 8888

spring:
  profiles:
    active: dafault
  cloud:
    config:
      server:
        git:
          username: RolandTapie
          password: KTRTgithub1
          uri: https://github.com/RolandTapie/ServerConfiguration
